### ISSUE TITLE
dependency to git

### ISSUE THREAD

**Issue by bollenn** [melexis/warnings-plugin#51]
```
mlx-warnings --junit --verbose ./build/unit_test/utest_summary/utest_aml_PercentageDecrease_report.xml

c:\apps\python35-32\lib\site-packages\setuptools_scm\utils.py:108: UserWarning: 'git' was not found

  warnings.warn("%r was not found" % name)

Traceback (most recent call last):

  File "C:\apps\Python35-32\Scripts\mlx-warnings-script.py", line 9, in <module>

    load_entry_point('mlx.warnings==0.0.10', 'console_scripts', 'mlx-warnings')()

  File "c:\apps\python35-32\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "c:\apps\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point

    return ep.load()

  File "c:\apps\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2229, in load

    return self.resolve()

  File "c:\apps\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "c:\apps\python35-32\lib\site-packages\mlx\warnings.py", line 19, in <module>

    __version__ = get_version()

  File "c:\apps\python35-32\lib\site-packages\setuptools_scm\__init__.py", line 119, in get_version

    parsed_version = _do_parse(root, parse)

  File "c:\apps\python35-32\lib\site-packages\setuptools_scm\__init__.py", line 97, in _do_parse

    "use git+https://github.com/user/proj.git#egg=proj" % root)
```

**Comment by Letme** [comment]
More like depencency on setuptools_scm

**Comment by Letme** [comment]
Can you upgrade setuptools-scm package?

**Comment by bollenn** [comment]
Adding git to the path makes it work
`UserWarning: 'git' was not found`

**Comment by Letme** [comment]
but setuptools-scm should handle that - so i would assume version of setuptools-scm is too old...

**Comment by Letme** [comment]
ah setuptools-scm in Windows has problems with git indeed. https://github.com/pypa/setuptools_scm/issues/182

**Comment by Letme** [comment]
can you recheck this with recent version of the plugin?

**Comment by Letme** [comment]
@bollenn ping on this :)

**Comment by Letme** [comment]
@bollenn can you please check if the recent version of plugin has the same problem?
