### ISSUE TITLE
Warnings plugin failing for latest version of setuptools_scm

### ISSUE THREAD

**Issue by bavovanachte** [melexis/warnings-plugin#68]
From this travis job: https://travis-ci.org/melexis/sphinx-traceability-extension/jobs/408095651

```
sphinx-latest runtests: commands[1] | mlx-warnings --sphinx --maxwarnings 7 --minwarnings 7 .tox/doc_html.log
  /home/travis/build/melexis/sphinx-traceability-extension$ /home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/bin/mlx-warnings --sphinx --maxwarnings 7 --minwarnings 7 .tox/doc_html.log 
/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/git.py:68: UserWarning: "/home/travis/build/melexis/sphinx-traceability-extension" is shallow and may cause errors
  warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))
/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/version.py:92: UserWarning: tag 'V2.5.2' no version found
  warnings.warn("tag %r no version found" % (tag,))
Traceback (most recent call last):
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/bin/mlx-warnings", line 7, in <module>
    from mlx.warnings import main
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/mlx/warnings.py", line 16, in <module>
    __version__ = get_version()
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 135, in get_version
    parsed_version = _do_parse(config)
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 88, in _do_parse
    config, "setuptools_scm.parse_scm"
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 45, in _version_from_entrypoint
    version = _call_entrypoint_fn(config, ep.load())
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 33, in _call_entrypoint_fn
    return fn(config.absolute_root, config=config)
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/git.py", line 131, in parse
    branch=branch,
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/version.py", line 184, in meta
    assert parsed_version is not None, "cant parse version %s" % tag
AssertionError: cant parse version V2.5.2
ERROR: InvocationError for command '/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/bin/mlx-warnings --sphinx --maxwarnings 7 --minwarnings 7 .tox/doc_html.log' (exited with code 1)
```

By adding the dependency `setuptools-scm==2.1.0` there, the issue is fixed.

**Comment by Letme** [comment]
hm, can we maybe open this issue in setuptools-scm rather than here?

**Comment by bavovanachte** [comment]
Done. https://github.com/pypa/setuptools_scm/issues/292

**Comment by bavovanachte** [comment]
Issue should be fixed upstream now. Will close this ticket when verified

**Comment by Letme** [comment]
Can you verify?

**Comment by JasperCraeghs** [comment]
We no longer use:
```
from setuptools_scm import get_version
version = get_version()
```
Now we use:
```
from pkg_resources import require
__version__ = require('mlx.warnings')[0].version
```
